### ISSUE TITLE
Crashes Game

### ISSUE THREAD

**Issue by Brian-Zombait** [PakL/SkipResearch-Factorio#2]
First, the buttons for all and no work fine.

When attempting to use the one time "yes" button, it crashes the game.

Error MainLoop.cpp:788: Exception at tick 10147: Error while running event on_gui_click (ID 1)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	__skipresearch__/control.lua:23: in function <__skipresearch__/control.lua:4>

**Comment by PakL** [comment]
I can't reproduce this issue. Can you post me the used Factorio version and a list of other mods you have installed?
